#execution_env=local
execution_env=remote
#appUrl=http://localhost/opencartsite/
#gmail= demo@gmail.com //ol
#password=demo@123 old
#password=demo@12345852 this used to check Sfailed test case

#new trial ninjatutorial demo config
appUrl=https://tutorialsninja.com/demo/
gmail=demo1234test@gmail.com
password=demo@1234